### ISSUE TITLE
Star Wars Search

### ISSUE THREAD

**Issue by Dichotomous247** [sdevalapurkar/starwars-search#2]
Can't align search bars and buttons

**Comment by Dichotomous247** [comment]
need buttons below each other and horizontally centered
<img width="349" alt="Screen Shot 2020-02-02 at 5 19 36 PM" src="https://user-images.githubusercontent.com/60080073/73619034-3c9af300-45e0-11ea-8000-23817054a149.png">

**Comment by sdevalapurkar** [comment]
are you still facing this issue or were you able to resolve it @Dichotomous247 ? :)

**Comment by Dichotomous247** [comment]
Yes I am still facing this issue @sdevalapurkar
