### ISSUE TITLE
Session Storage

### ISSUE THREAD

**Issue by Dichotomous247** [sdevalapurkar/starwars-search#7]
Having trouble pulling data from session from session storage and pushing into html.

**Comment by sdevalapurkar-bcgov** [comment]
to retrieve from session storage you need to use the getitem function:

`sessionStorage.getItem("nameofitem")`

**Comment by sdevalapurkar-bcgov** [comment]
once you have access to the value you are looking for in js, you can inject it into your html

**Comment by sdevalapurkar-bcgov** [comment]
https://stackoverflow.com/questions/50271492/injecting-variable-value-from-js-to-html-file

**Comment by sdevalapurkar-bcgov** [comment]
https://stackoverflow.com/questions/27692303/injecting-data-in-html-with-javascript
